GET http://localhost:6000

###
GET http://localhost:6000/protected
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDgwMTQ0MDYsImV4cCI6MTcwODAxNTAwNiwiYXVkIjoiQUJDIiwiaXNzIjoid3d3Lmhhc2FuLmNvbSJ9.DYb_JRZQpBJDEGEG-3jYrzVMFjm7TWTgydWYIsnIwG2VVzRgHEvE_rETgvtQot69UzFSG8sLPvB13Ka8v5-OeJv7mveviYpHTonoBYahp5U677MvOC4gbjENxaXPNWiFq6nvVwZWpbEutmxCLuqVFiOcry5xkiCB0hsC-TjOvKI8ht-LAxwGwV2H8xpaaBXua0WgnV_TzHZwe2-m40SsTufcj-tvmxwxg0YOwaydO0_jS-l6jOxWtv7RqFkLIQX-057LVTRK1f0T0oMy2pO8BnyEuYbjVc6hmljm4HFEZn16izxDlX68hsYLnEKz_4VuTFAxCrHz6SXHtt1TAv5nJdgnLnQLvWNP2hnoAGUj8HbzhBknJLG0gB4lwrvoo0wuZovwy-z3Ld6RhhtlJ5-mHeAiAg2aV_N_8OYwEzWMgEzpIuACwVBFxQMNx500WDHMJ8k3TJ9sZnTBHg8dz4yZ1JrEpccsgUSEDMODkiYmBjFl6CatkwxoIKrdabcA8I8a